#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname *.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="/usr/bin/env java"

if [ -n "${SERVER_MAXPERM}" ]
then
  STARTCMD="${STARTCMD} -XX:MaxPermSize=${SERVER_MAXPERM}"
fi

if [ -n "${SERVER_MAXHEAP}" ]
then
  STARTCMD="${STARTCMD} -Xmx${SERVER_MAXHEAP}"
fi

if [ -n "${SERVER_MINHEAP}" ]
then
  STARTCMD="${STARTCMD} -Xms${SERVER_MINHEAP}"
fi

pushd /minecraft > /dev/null
  echo "> starting minecraft service"
  exec ${STARTCMD} ${JAVA_OPTS} -jar ${FORGE_JAR} ${SERVER_OPTS}
popd > /dev/null
