#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname \*.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="/usr/bin/env java"

if [ -n "${MINECRAFT_MAXHEAP}" ]
then
  STARTCMD="${STARTCMD} -Xmx${MINECRAFT_MAXHEAP}"
fi

if [ -n "${MINECRAFT_MINHEAP}" ]
then
  STARTCMD="${STARTCMD} -Xms${MINECRAFT_MINHEAP}"
fi

pushd ${MINECRAFT_GAME_DIR} >/dev/null
  echo "> starting minecraft service"
  exec ${STARTCMD} ${JAVA_OPTS} -jar ${FORGE_JAR} ${MINECRAFT_OPTS}
popd >/dev/null
