#!/usr/bin/env bash
# Usage: manage whitelist-remove <player>
# Summary: Remove player from whitelist
# Help: This command is used to remove a player from the whitelist on the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

VALUE=${1}

if [ -z $VALUE ]
then
  echo "Provider a player"
  exit 1
fi

manage-mcrcon "whitelist remove ${VALUE}"
