#!/usr/bin/env bash
# Usage: manage deop <player>
# Summary: Deop a specific player
# Help: This command is used to deop a specific player on the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

VALUE=${1}

if [ -z "${VALUE}" ]
then
  echo "Provide a player"
  exit 1
fi

manage-mcrcon "deop ${VALUE}"
