#!/usr/bin/env bash
# Usage: manage whitelist-off
# Summary: Disable the whitelist
# Help: This command is used to disable the whitelist on the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

manage-mcrcon "whitelist off"
