#!/usr/bin/env bash
# Usage: manage start
# Summary: Start the server
# Help: This command is used to really start the server process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  echo "Server is already running"
else
  manage-prepare && manage-config && /usr/bin/env java -Xmx${SERVER_MAXHEAP} -Xms${SERVER_MINHEAP} -jar ${_MANAGE_ROOT}/${FORGE_JAR} ${SERVER_OPTS}
fi
