#!/usr/bin/env bash
# Usage: manage say <message>
# Summary: Say something on the server
# Help: This command is used to send a chat message to the server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

VALUE=${1}

if [ -z "${VALUE}" ]
then
  echo "Provide a message"
  exit 1
fi

manage-mcrcon "say ${VALUE}"
