#!/usr/bin/env bash
# Usage: manage restart
# Summary: Restart the minecraft server
# Help: This command is used to really restart the minecraft server process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if pgrep -f ${FORGE_JAR}
then
  manage-stop && manage-start
else
  manage-start
fi
