#!/usr/bin/env bash

declare -x MINECRAFT_OPTIONALS_DIR
[[ -z "${MINECRAFT_OPTIONALS_DIR}" ]] && MINECRAFT_OPTIONALS_DIR="${MINECRAFT_GAME_DIR}/optionals"

declare -x MINECRAFT_MODS_DIR
[[ -z "${MINECRAFT_MODS_DIR}" ]] && MINECRAFT_MODS_DIR="${MINECRAFT_GAME_DIR}/mods"

declare -x MINECRAFT_DYNMAP_DIR
[[ -z "${MINECRAFT_DYNMAP_DIR}" ]] && MINECRAFT_DYNMAP_DIR="${MINECRAFT_DATA_DIR}/dynmap"

declare -x MINECRAFT_ENABLE_DYNMAP
[[ -z "${MINECRAFT_ENABLE_DYNMAP}" ]] && MINECRAFT_ENABLE_DYNMAP="${SERVER_DYNMAP:-true}"

true
