---
name: v43.3

"on":
  push:
    branches:
      - master
    paths:
      - v43.3/*
      - .github/workflows/v43.3.yml
  pull_request:
    branches:
      - master
    paths:
      - v43.3/*
      - .github/workflows/v43.3.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            webhippie/minecraft-forge
            quay.io/webhippie/minecraft-forge
            ghcr.io/dockhippie/minecraft-forge
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Hub login
        id: login1
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        id: login2
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Ghcr login
        id: login3
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build amd64
        id: amd64
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: v43.3/
          provenance: false
          file: v43.3/Dockerfile.amd64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-forge:43.3-amd64
            quay.io/webhippie/minecraft-forge:43.3-amd64
            ghcr.io/dockhippie/minecraft-forge:43.3-amd64

      - name: Build arm64
        id: arm64
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: v43.3/
          provenance: false
          file: v43.3/Dockerfile.arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-forge:43.3-arm64
            quay.io/webhippie/minecraft-forge:43.3-arm64
            ghcr.io/dockhippie/minecraft-forge:43.3-arm64

      - name: Hub manifest
        id: manifest1
        uses: actionhippie/manifest@6e645218a2939c5ec0f239ed80e5b7ff903b9cc2 # v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          template: webhippie/minecraft-forge:43.3-ARCH
          target: webhippie/minecraft-forge:43.3
          ignore_missing: true

      - name: Quay manifest
        id: manifest2
        uses: actionhippie/manifest@6e645218a2939c5ec0f239ed80e5b7ff903b9cc2 # v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          template: quay.io/webhippie/minecraft-forge:43.3-ARCH
          target: quay.io/webhippie/minecraft-forge:43.3
          ignore_missing: true

      - name: Ghcr manifest
        id: manifest3
        uses: actionhippie/manifest@6e645218a2939c5ec0f239ed80e5b7ff903b9cc2 # v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          template: ghcr.io/dockhippie/minecraft-forge:43.3-ARCH
          target: ghcr.io/dockhippie/minecraft-forge:43.3
          ignore_missing: true

...
