---
name: v43.0

"on":
  push:
    branches:
      - master
    paths:
      - v43.0/*
      - .github/workflows/v43.0.yml
  pull_request:
    branches:
      - master
    paths:
      - v43.0/*
      - .github/workflows/v43.0.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            webhippie/minecraft-forge
            quay.io/webhippie/minecraft-forge
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Hub login
        id: login1
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        id: login2
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build amd64
        id: amd64
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: v43.0/
          file: v43.0/Dockerfile.amd64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-forge:43.0-amd64
            quay.io/webhippie/minecraft-forge:43.0-amd64

      - name: Build arm64
        id: arm64
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: v43.0/
          file: v43.0/Dockerfile.arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-forge:43.0-arm64
            quay.io/webhippie/minecraft-forge:43.0-arm64

      - name: Hub manifest
        id: manifest1
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          template: webhippie/minecraft-forge:43.0-ARCH
          target: webhippie/minecraft-forge:43.0
          ignore_missing: true

      - name: Quay manifest
        id: manifest2
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          template: quay.io/webhippie/minecraft-forge:43.0-ARCH
          target: quay.io/webhippie/minecraft-forge:43.0
          ignore_missing: true

...
